services:
  - type: web
    name: hostel-app
    runtime: python
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://joshi12345:joshi12345@notify.fvlhsso.mongodb.net/?appName=notify
      - key: MONGODB_DB
        value: hostel_db
      - key: MONGODB_STUDENTS_COLLECTION
        value: students
      - key: MONGODB_ROOMS_COLLECTION
        value: rooms
      - key: MONGODB_TRANSACTIONS_COLLECTION
        value: transactions
